title: Networks in Science of Science
description: "A NetSci 2026 Satellite Workshop"

timezone: America/Boston

navigation:
  Home: "/"
  Call for Papers: "/cfp"
  Accepted Papers: "/papers"
  Speakers: "/speakers"
  Schedule: "/schedule"
  Organizers: "/organizers"
  # 2023: "/2023"
  # 2024: "/2024"

markdown: kramdown

kramdown:
  parse_span_html: true
  parse_block_html: true

plugins:
  - jekyll-seo-tag

exclude: ['README.md', 'Gemfile', 'Gemfile.lock']
